name: main
on: push

concurrency:
  group: ${{ github.head_ref || github.workflow }}
  cancel-in-progress: true

jobs:
  # chromatic-deployment:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: fix memory
  #       run: export NODE_OPTIONS="--max-old-space-size=8192"
  #     - name: Install dependencies
  #       run: yarn
  #     - name: echo node
  #       run: node -v
  #     - name: Publish to Chromatic
  #       uses: chromaui/action@v1
  #       with:
  #         projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: install-dependencies
        run: yarn
  # eslint:
  #   runs-on: ubuntu-latest
  #   needs: [install-dependencies]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Restore dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #     - name: Eslint
  #       run: yarn lint
  # type-check:
  #   runs-on: ubuntu-latest
  #   needs: [install-dependencies]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Restore dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #     - name: Check types
  #       run: yarn type-check
  # unit-tests:
  #   runs-on: ubuntu-latest
  #   needs: [install-dependencies]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Restore dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #     - name: Run tests
  #       run: yarn test
  # e2e-tests
  build:
    runs-on: ubuntu-latest
    # needs: [eslint, type-check, unit-tests]
    needs: [install-dependencies]
    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Build the app
        run: yarn build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist
      - name: Publish to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
